@startuml
package "Medical Information System" {

interface Storage {
  + returnPatient(patientID)
  + returnDoctor(doctorID)
}

class Patient {
  - id : int
  - fullName : string
  - contactInfo : string
  - recordStatus : string
  + bookAppointment()
  + rescheduleAppointment()
  + cancelAppointment()
  + addVisit()
}

class "Information System" {
  - id : int
  - fullName : string
  + createAppointment(patientID, doctorID, appointmentDate, appointmentTime)
  + rescheduleAppointment()
  + registerPatient()
  + removePatientFromRecord()
  + confirmRegistration()
  + removeFromRecord()
}

class Doctor {
  - id : int
  - fullName : string
  - specialty : string
  - schedule : Slot[]
  + provideAvailableSlots()
  + conductAppointment()
  + recordVisitResults()
}

class Shedule {
  - private shedule : List<Appointment>
  + showShedule()
  + showAvailableSlots()
}

class Appointment {
  - id : int
  - date : Date
  - time : Time
  - status : string
  - doctor : &Doctor
  + create()
  + reschedule()
  + cancel()
  + recordVisit()
}

class MedicalRecord {
  - id : int
  - history : Visit[]
  - status : Bool
  + archive()
}

class Notification {
  - id : int
  - type : string
  - message : string
  - sentDate : Date
  + send()
}

Patient "1" -- "1" MedicalRecord
Patient "1" -- "*" Appointment
Patient -- Notification
Doctor -- Notification
Doctor "1" -- "*" Appointment

"Information System" *-- Shedule
"Information System" *-- Notification
"Information System" *-- "MedicalRecord"
"Information System" ..|> Storage
Shedule *-- Appointment
}
@enduml
