@startuml
left to right direction

actor Пациент
actor "Информационная система регистрации"
actor Врач
actor Администратор

rectangle "Медицинская информационная система" {
    usecase "Запись на приём" as BA
    usecase "Перенос записи" as RA
    usecase "Проведение приёма" as RV
    usecase "Управление учётом пациентов" as CPR
}

' Patient interactions
Пациент -- BA
Пациент -- RA

' Обязанности информационной системы регистрации
"Информационная система регистрации" -- BA
"Информационная система регистрации"-- RA
"Информационная система регистрации"-- CPR

' Обязанности доктора
Врач -- BA
Врач -- RA
Врач -- RV

' Обязанности администратора
Администратор -- CPR
@enduml
