@startuml
left to right direction

actor Пациент
actor "Информационная система регистрации"
actor Врач
actor Администратор

rectangle "Медицинская информационная система" {
    usecase "Запись на приём" as BA
    usecase "Перенос записи" as RA
    usecase "Фиксация факта приёма" as RV
    usecase "Постановка на учёт" as RPR
    usecase "Снятие с учёта" as RMR
}

' Patient interactions
Пациент -- BA
Пациент -- RA

' Обязанности информационной системы регистрации
"Информационная система регистрации" -- BA
"Информационная система регистрации"-- RA
"Информационная система регистрации"-- RPR
"Информационная система регистрации"-- RMR

' Обязанности доктора
Врач -- BA
Врач -- RA
Врач -- RV

' Обязанности администратора
Администратор -- RPR
Администратор -- RMR
@enduml
