@startuml
title Reschedule Appointment (Перенос записи)

actor Patient

== Начало процесса переноса записи ==
Patient -> Appointment : Запрос на перенос записи reshedule(appointmentId)
Appointment -> Shedule : getAvailableSlots()
Shedule -> Appointment : List[]availableSlots
Appointment -> Patient : showAvailableSlots(slots)

== Пациент выбирает новове время ==
Patient -> Appointment : chooseNewTime(newTimeSlot)
Appointment -> Shedule : updateShedule()

== Уведомление пациента о переносе записи ==
Shedule -> InformationSystem : sendNotification()
InformationSystem -> Notification : send()
Notification --> Patient : Пациент получает уведомление

@enduml
